/**
 * Jindo Mobile Component
 * @version 1.4.0
 * NHN_Library:Jindo_Mobile_Component-1.4.0;JavaScript Mobile Components for Jindo;
 */


jindo.Component=jindo.$Class({_htEventHandler:null,_htOption:null,$init:function(){var aInstance=this.constructor.getInstance();aInstance.push(this);this._htEventHandler={};this._htOption={};this._htOption._htSetter={};},option:function(sName,vValue){switch(typeof sName){case"undefined":return this._htOption;case"string":if(typeof vValue!="undefined"){if(sName=="htCustomEventHandler"){if(typeof this._htOption[sName]=="undefined"){this.attach(vValue);}else{return this;}}
this._htOption[sName]=vValue;if(typeof this._htOption._htSetter[sName]=="function"){this._htOption._htSetter[sName](vValue);}}else{return this._htOption[sName];}
break;case"object":for(var sKey in sName){if(sKey=="htCustomEventHandler"){if(typeof this._htOption[sKey]=="undefined"){this.attach(sName[sKey]);}else{continue;}}
this._htOption[sKey]=sName[sKey];if(typeof this._htOption._htSetter[sKey]=="function"){this._htOption._htSetter[sKey](sName[sKey]);}}
break;}
return this;},optionSetter:function(sName,fSetter){switch(typeof sName){case"undefined":return this._htOption._htSetter;case"string":if(typeof fSetter!="undefined"){this._htOption._htSetter[sName]=jindo.$Fn(fSetter,this).bind();}else{return this._htOption._htSetter[sName];}
break;case"object":for(var sKey in sName){this._htOption._htSetter[sKey]=jindo.$Fn(sName[sKey],this).bind();}
break;}
return this;},fireEvent:function(sEvent,oEvent){oEvent=oEvent||{};var fInlineHandler=this['on'+sEvent],aHandlerList=this._htEventHandler[sEvent]||[],bHasInlineHandler=typeof fInlineHandler=="function",bHasHandlerList=aHandlerList.length>0;if(!bHasInlineHandler&&!bHasHandlerList){return true;}
aHandlerList=aHandlerList.concat();oEvent.sType=sEvent;if(typeof oEvent._aExtend=='undefined'){oEvent._aExtend=[];oEvent.stop=function(){if(oEvent._aExtend.length>0){oEvent._aExtend[oEvent._aExtend.length-1].bCanceled=true;}};}
oEvent._aExtend.push({sType:sEvent,bCanceled:false});var aArg=[oEvent],i,nLen;for(i=2,nLen=arguments.length;i<nLen;i++){aArg.push(arguments[i]);}
if(bHasInlineHandler){fInlineHandler.apply(this,aArg);}
if(bHasHandlerList){var fHandler;for(i=0,fHandler;(fHandler=aHandlerList[i]);i++){fHandler.apply(this,aArg);}}
return!oEvent._aExtend.pop().bCanceled;},attach:function(sEvent,fHandlerToAttach){if(arguments.length==1){jindo.$H(arguments[0]).forEach(jindo.$Fn(function(fHandler,sEvent){this.attach(sEvent,fHandler);},this).bind());return this;}
var aHandler=this._htEventHandler[sEvent];if(typeof aHandler=='undefined'){aHandler=this._htEventHandler[sEvent]=[];}
aHandler.push(fHandlerToAttach);return this;},detach:function(sEvent,fHandlerToDetach){if(arguments.length==1){jindo.$H(arguments[0]).forEach(jindo.$Fn(function(fHandler,sEvent){this.detach(sEvent,fHandler);},this).bind());return this;}
var aHandler=this._htEventHandler[sEvent];if(aHandler){for(var i=0,fHandler;(fHandler=aHandler[i]);i++){if(fHandler===fHandlerToDetach){aHandler=aHandler.splice(i,1);break;}}}
return this;},detachAll:function(sEvent){var aHandler=this._htEventHandler;if(arguments.length){if(typeof aHandler[sEvent]=='undefined'){return this;}
delete aHandler[sEvent];return this;}
for(var o in aHandler){delete aHandler[o];}
return this;}});jindo.Component.factory=function(aObject,htOption){var aReturn=[],oInstance;if(typeof htOption=="undefined"){htOption={};}
for(var i=0,el;(el=aObject[i]);i++){oInstance=new this(el,htOption);aReturn[aReturn.length]=oInstance;}
return aReturn;};jindo.Component.getInstance=function(){if(typeof this._aInstance=="undefined"){this._aInstance=[];}
return this._aInstance;};if(typeof jindo.m=="undefined"&&typeof Node!="undefined"){var ___Old__addEventListener___=Node.prototype.addEventListener;Node.prototype.addEventListener=function(type,listener,useCapture){var callee=arguments.callee;if(callee&&type==="click"&&this.tagName==="A"){(this.___listeners___||(this.___listeners___=[])).push({listener:listener,useCapture:useCapture});}
return ___Old__addEventListener___.apply(this,arguments);};var ___Old__removeEventListener___=Node.prototype.removeEventListener;Node.prototype.removeEventListener=function(type,listener,useCapture){var callee=arguments.callee;if(callee&&type==="click"&&this.tagName==="A"){if(this.___listeners___){this.___listeners___.pop();}}
return ___Old__removeEventListener___.apply(this,arguments);};}
jindo.m=(function(){var __M__=jindo.$Class({$init:function(){this._initVar();this._initDeviceInfo();this._attachEvent();},_initVar:function(){this.MOVETYPE={0:'hScroll',1:'vScroll',2:'dScroll',3:'tap',4:'longTap',5:'doubleTap',6:'pinch',7:'rotate',8:'pinch-rotate'};this.sVersion="1.3.1";this._isVertical=null;this._nPreWidth=-1;this._nRotateTimer=null;this._htHandler={};this._htDeviceInfo={};},_getOrientationChangeEvt:function(){var bEvtName='onorientationchange'in window?'orientationchange':'resize';var htInfo=this.getDeviceInfo();if((htInfo.android&&htInfo.version==="2.1")){bEvtName='resize';}
return bEvtName;},_getVertical:function(){var bVertical=null,sEventType=this._getOrientationChangeEvt();if(sEventType==="resize"){var screenWidth=document.documentElement.clientWidth;if(screenWidth<this._nPreWidth){bVertical=true;}else if(screenWidth==this._nPreWidth){bVertical=this._isVertical;}else{bVertical=false;}
this._nPreWidth=screenWidth;}else{var windowOrientation=window.orientation;if(windowOrientation===0||windowOrientation==180){bVertical=true;}else if(windowOrientation==90||windowOrientation==-90){bVertical=false;}}
return bVertical;},_attachEvent:function(){this._rotateEvent=jindo.$Fn(this._onOrientationChange,this).attach(window,this._getOrientationChangeEvt()).attach(window,"load");this._pageShowEvent=jindo.$Fn(this._onPageshow,this).attach(window,"pageshow");},_initDeviceInfo:function(){var sName=navigator.userAgent;var ar=null;function f(s,h){return((h||"").indexOf(s)>-1);}
this._htDeviceInfo.iphone=f('iPhone',sName);this._htDeviceInfo.ipad=f('iPad',sName);this._htDeviceInfo.android=f('Android',sName);this._htDeviceInfo.galaxyTab=f('SHW-M180',sName);this._htDeviceInfo.galaxyTab2=f('SHW-M380',sName);this._htDeviceInfo.galaxyK=f('SHW-M130K',sName);this._htDeviceInfo.galaxyU=f('SHW-M130L',sName);this._htDeviceInfo.galaxyS=f('SHW-M110',sName);this._htDeviceInfo.galaxyS2=f('SHW-M250',sName);this._htDeviceInfo.galaxyS2LTE=f('SHV-E110',sName);this._htDeviceInfo.galaxyS3=f('SHV-E210',sName)||f('SHW-M440',sName);this._htDeviceInfo.galaxyNote=f('SHV-E160',sName);this._htDeviceInfo.galaxyNexus=f('Galaxy Nexus',sName);this._htDeviceInfo.optimusLte2=f('LG-F160',sName);this._htDeviceInfo.optimusVu=f('LG-F100',sName);this._htDeviceInfo.optimusLte=f('LG-LU6200',sName)||f('LG-SU640',sName)||f('LG-F120K',sName);this._htDeviceInfo.version='';this._htDeviceInfo.bChrome=this._htDeviceInfo.android&&(f('CrMo',sName)||f('Chrome',sName));this._htDeviceInfo.bInapp=false;if(this._htDeviceInfo.iphone||this._htDeviceInfo.ipad){ar=sName.match(/OS\s([\d|\_]+\s)/i);if(ar!==null&&ar.length>1){this._htDeviceInfo.version=ar[1];}}else if(this._htDeviceInfo.android){ar=sName.match(/Android\s([^\;]*)/i);if(ar!==null&&ar.length>1){this._htDeviceInfo.version=ar[1];}}
this._htDeviceInfo.version=this._htDeviceInfo.version.replace(/\_/g,'.');for(var x in this._htDeviceInfo){if(typeof this._htDeviceInfo[x]=="boolean"&&this._htDeviceInfo[x]&&this._htDeviceInfo.hasOwnProperty(x)){this._htDeviceInfo.name=x;}}
this._htDeviceInfo.samsung=f('GT-',sName)||f('SCH-',sName)||f('SHV-',sName)||f('SHW-',sName)||f('SPH',sName)||f('SWT-',sName)||f('SGH-',sName);this._htDeviceInfo.lg=f('LG-',sName);this._htDeviceInfo.pantech=f('IM-',sName);if(this._htDeviceInfo.iphone||this._htDeviceInfo.ipad){if(!f('Safari',sName)){this._htDeviceInfo.bInapp=true;}}else if(this._htDeviceInfo.android){sName=sName.toLowerCase();if(f('inapp',sName)||f('app',sName.replace('applewebkit',''))){this._htDeviceInfo.bInapp=true;}}},_onOrientationChange:function(we){var self=this;if(we.type==="load"){this._nPreWidth=document.documentElement.clientWidth;if(!this._htDeviceInfo.bInapp&&(this._htDeviceInfo.iphone||this._htDeviceInfo.ipad||this._getOrientationChangeEvt()!=="resize")){this._isVertical=this._getVertical();}else{if(this._nPreWidth>document.documentElement.clientHeight){this._isVertical=false;}else{this._isVertical=true;}}
return;}
if(this._getOrientationChangeEvt()==="resize"){setTimeout(function(){self._orientationChange(we);},0);}else{var nTime=200;if(this.getDeviceInfo().android){nTime=500;}
clearTimeout(this._nRotateTimer);this._nRotateTimer=setTimeout(function(){self._orientationChange(we);},nTime);}},_orientationChange:function(we){var nPreVertical=this._isVertical;this._isVertical=this._getVertical();if(jindo.$Agent().navigator().mobile||jindo.$Agent().os().ipad){if(nPreVertical!==this._isVertical){this.fireEvent("mobilerotate",{isVertical:this._isVertical});}}else{this.fireEvent("mobilerotate",{isVertical:this._isVertical});}},bindRotate:function(fHandlerToBind){var aHandler=this._htHandler["mobilerotate"];if(typeof aHandler=='undefined'){aHandler=this._htHandler["mobilerotate"]=[];}
aHandler.push(fHandlerToBind);this.attach("mobilerotate",fHandlerToBind);},unbindRotate:function(fHandlerToUnbind){var aHandler=this._htHandler["mobilerotate"];if(aHandler){for(var i=0,fHandler;(fHandler=aHandler[i]);i++){if(fHandler===fHandlerToUnbind){aHandler.splice(i,1);this.detach("mobilerotate",fHandlerToUnbind);break;}}}},_onPageshow:function(we){this._isVertical=this._getVertical();var self=this;setTimeout(function(){self.fireEvent("mobilePageshow",{});},300);},bindPageshow:function(fHandlerToBind){var aHandler=this._htHandler["mobilePageshow"];if(typeof aHandler=='undefined'){aHandler=this._htHandler["mobilePageshow"]=[];}
aHandler.push(fHandlerToBind);this.attach("mobilePageshow",fHandlerToBind);},unbindPageshow:function(fHandlerToUnbind){var aHandler=this._htHandler["mobilePageshow"];if(aHandler){for(var i=0,fHandler;(fHandler=aHandler[i]);i++){if(fHandler===fHandlerToUnbind){aHandler.splice(i,1);this.detach("mobilePageshow",fHandlerToUnbind);break;}}}},getDeviceInfo:function(){return this._htDeviceInfo;},isVertical:function(){if(this._isVertical===null){return this._getVertical();}else{return this._isVertical;}},getNodeElement:function(el){while(el.nodeType!=1){el=el.parentNode;}
return el;},getCssOffset:function(element){var htOffset;if(jindo.m.getDeviceInfo().android&&parseInt(jindo.m.getDeviceInfo().version,10)===3){htOffset=jindo.m._getCssOffsetFromStyle(element);}else{if('WebKitCSSMatrix'in window&&'m11'in new WebKitCSSMatrix()){htOffset=jindo.m._getCssOffsetFromCSSMatrix(element);}else{htOffset=jindo.m._getCssOffsetFromStyle(element);}}
return htOffset;},_getCssOffsetFromStyle:function(element){var nTop=nLeft=0,s=element.style[jindo.m.getCssPrefix()+"Transform"];if(!!s&&s.length>0){aTemp=s.match(/translate.{0,2}\((.*)\)/);if(!!aTemp&&aTemp.length>1){var a=aTemp[1].split(',');if(!!a&&a.length>1){nTop=parseInt(a[1],10);nLeft=parseInt(a[0],10);}}}
return{top:nTop,left:nLeft};},_getCssOffsetFromCSSMatrix:function(element){var curTransform=new WebKitCSSMatrix(window.getComputedStyle(element).webkitTransform);return{top:curTransform.m42,left:curTransform.m41};},attachTransitionEnd:function(element,fHandlerToBind){var nVersion=+jindo.$Jindo().version.replace(/[a-z.]/gi,"");if(nVersion>=151){element._jindo_fn_=jindo.$Fn(fHandlerToBind,this).attach(element,"transitionend");}else{element.addEventListener('webkitTransitionEnd',fHandlerToBind,false);}},detachTransitionEnd:function(element,fHandlerToUnbind){var nVersion=+jindo.$Jindo().version.replace(/[a-z.]/gi,"");if(nVersion>=151){if(element._jindo_fn_){element._jindo_fn_.detach(element,"transitionend");delete element._jindo_fn_;}}else{element.removeEventListener('webkitTransitionEnd',fHandlerToUnbind,false);}},getCssPrefix:function(){var sCssPrefix="";if(typeof document.body.style.MozTransition!=="undefined"){sCssPrefix="Moz";}else if(typeof document.body.style.webkitTransition!=="undefined"){sCssPrefix="webkit";}else if(typeof document.body.style.OTransition!=="undefined"){sCssPrefix="O";}
return sCssPrefix;},getClosest:function(sSelector,elBaseElement){var elClosest;var welBaseElement=jindo.$Element(elBaseElement);var reg=/<\/?(?:h[1-5]|[a-z]+(?:\:[a-z]+)?)[^>]*>/ig;if(reg.test(sSelector)){if("<"+elBaseElement.tagName.toUpperCase()+">"==sSelector.toUpperCase()){elClosest=elBaseElement;}else{elClosest=welBaseElement.parent(function(v){if("<"+v.$value().tagName.toUpperCase()+">"==sSelector.toUpperCase()){return v;}});elClosest=elClosest.length?elClosest[0].$value():false;}}else{if(sSelector.indexOf('.')==0){sSelector=sSelector.substring(1,sSelector.length)}
if(welBaseElement.hasClass(sSelector)){elClosest=elBaseElement;}else{elClosest=welBaseElement.parent(function(v){if(v.hasClass(sSelector)){return v;}});elClosest=elClosest.length?elClosest[0].$value():false;}}
return elClosest;},_isUseCss3d:function(isFlicking){if(typeof isFlicking==='undefined'){isFlicking=false;}
var bRet=false;if(this._htDeviceInfo.iphone||this._htDeviceInfo.ipad){bRet=true;}else if(this._htDeviceInfo.android){var s=navigator.userAgent.match(/\(.*\)/)[0];function f(s,h){return((h||"").indexOf(s)>-1);}
var isUseCss3d=f('SHW-',s)||f('SHV-',s)||f('GT-',s)||f('SCH-',s)||f('SGH-',s)||f('SPH-',s)||f('LG-F160',s)||f('LG-F100',s);var isEtc=(f('SHW-M250',s)&&(this._htDeviceInfo.version<="4.0.3"))||f('SHW-M420',s)||f('SHW-M200',s)||f('GT-S7562',s);if(!isFlicking){isEtc=isEtc||f('SHV-E110',s);}
if(this._htDeviceInfo.version>="4.0.3"&&isUseCss3d&&!isEtc){bRet=true;}}
return bRet;},_isUseFixed:function(){var isFixed=false;if(this._htDeviceInfo.bChrome||(this._htDeviceInfo.android&&parseInt(this._htDeviceInfo.version,10)>=3)||((this._htDeviceInfo.iphone||this._htDeviceInfo.ipad)&&(parseInt(this._htDeviceInfo.version,10)>=5))){isFixed=true;}
return isFixed;},_isUseTimingFunction:function(){var bUse=this._isUseCss3d();if(this._htDeviceInfo.android){bUse=false;}
return bUse},_clientSize:function(isMinSize){if(typeof isMinSize==='undefined'){isMinSize=false;}
var oSize={};var oRet=jindo.$Document().clientSize();var nVersion=parseInt(this._htDeviceInfo.version,10);if((this._htDeviceInfo.ipad||this._htDeviceInfo.iphone)||this._htDeviceInfo.bChrome){if(isMinSize&&this._htDeviceInfo.iphone){oRet.height=this.isVertical()?356:268;}
return oRet;}
switch(this._htDeviceInfo.name){case"galaxyTab":oSize={portrait:400,landscape:683};oSize.landscape-=92;oSize.portrait-=66;break;case"galaxyTab2":oSize={portrait:1280,landscape:800};oSize.landscape-=152;oSize.portrait-=152;break;case"galaxyS":oSize={portrait:320,landscape:533};oSize.landscape-=81;oSize.portrait-=81;break;case"galaxyS2LTE":case"galaxyS2":oSize={portrait:320,landscape:533};if(nVersion==4){oSize.landscape-=77;oSize.portrait-=77;}else{oSize.landscape-=83;oSize.portrait-=83;}
break;case"galaxyS3":oSize={portrait:360,landscape:640};oSize.landscape-=73;oSize.portrait-=73;break;case"galaxyNote":oSize={portrait:400,landscape:640};if(nVersion==4){oSize.landscape-=77;oSize.portrait-=77;}else{oSize.landscape-=103;oSize.portrait-=103;}
break;case"galaxyNexus":oSize={portrait:360,landscape:598};oSize.landscape-=83;oSize.portrait-=83;break;case"optimusLte":oSize={portrait:360,landscape:640};oSize.landscape-=73;oSize.portrait-=73;break;case"optimusLte2":oSize={portrait:360,landscape:640};oSize.landscape-=73;oSize.portrait-=73;break;case"optimusVu":oSize={portrait:439,landscape:585};oSize.landscape-=73;oSize.portrait-=73;break;}
if(this.isVertical()){if(isMinSize||(oSize.landscape&&oSize.landscape>oRet.height)){oRet.height=oSize.landscape;}}else{if(isMinSize||(oSize.portrait&&oSize.portrait>oRet.height)){oRet.height=oSize.portrait;}}
return oRet;},_getAdressSize:function(){var nSize=0;if(this._htDeviceInfo.bInapp){return nSize;}
var nVersion=parseInt(this._htDeviceInfo.version,10);if(this._htDeviceInfo.iphone){nSize=60;}else if(this._htDeviceInfo.android){switch(this._htDeviceInfo.name){case"galaxyTab":nSize=66;break;case"galaxyTab2":nSize=48;break;case"galaxyS":nSize=56;break;case"galaxyS2LTE":case"galaxyS2":if(nVersion==4){nSize=52;}else{nSize=58;}
break;case"galaxyS3":nSize=48;break;case"galaxyNote":if(nVersion==4){nSize=52;}else{nSize=78;}
break;case"galaxyNexus":nSize=52;break;case"optimusVu":case"optimusLte":case"optimusLte2":nSize=48;break;}}
return nSize;}}).extend(jindo.Component);return new __M__();})();jindo.UIComponent=jindo.$Class({$init:function(){this._bIsActivating=false;},isActivating:function(){return this._bIsActivating;},activate:function(){if(this.isActivating()){return this;}
this._bIsActivating=true;if(arguments.length>0){this._onActivate.apply(this,arguments);}else{this._onActivate();}
return this;},deactivate:function(){if(!this.isActivating()){return this;}
this._bIsActivating=false;if(arguments.length>0){this._onDeactivate.apply(this,arguments);}else{this._onDeactivate();}
return this;}}).extend(jindo.Component);window.requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||function(callback){return setTimeout(callback,0);};})();window.cancelRequestAnimationFrame=(function(){return window.cancelRequestAnimationFrame||window.webkitCancelRequestAnimationFrame||clearTimeout;})();jindo.m.CoreScroll=jindo.$Class({$init:function(el,htUserOption){this.option({bActivateOnload:true,bUseHScroll:false,bUseVScroll:true,bUseMomentum:true,nDeceleration:0.0006,nOffsetTop:0,nOffsetBottom:0,nHeight:0,nWidth:0,bUseBounce:true,bUseHighlight:true,sClassPrefix:'scroll_',bUseCss3d:jindo.m._isUseCss3d(),bUseTimingFunction:jindo.m._isUseTimingFunction(),sListElement:'',nRatio:1.5,bUseTranslate:true});this.option(htUserOption||{});this._initVar();this._setWrapperElement(el);if(this.option("bActivateOnload")){this.activate();}},_initVar:function(){var htDeviceInfo=jindo.m.getDeviceInfo();this.isPositionBug=htDeviceInfo.android&&!htDeviceInfo.bChrome;this.isIos=htDeviceInfo.ipad||htDeviceInfo.iphone;this.nVersion=parseFloat(htDeviceInfo.version.substr(0,3));this.sCssPrefix=jindo.m.getCssPrefix();this.sTranOpen=null;this.sTranEnd=null;this.nWrapperW=null;this.nWrapperH=null;this.nScrollW=null;this.nScrollH=null;this.nMaxScrollLeft=null;this.nMaxScrollTop=null;this.nMinScrollTop=null;this.bUseHScroll=null;this.bUseVScroll=null;this._nLeft=0;this._nTop=0;this.bUseHighlight=this.option("bUseHighlight");this._aAni=[];this._nAniTimer=null;this._nFixePositionBugTimer=null;this._oTouch=null;this._oDynamicScrollPlugin=null;this._bUseDynamicScroll=false;this._isAnimating=false;this._isControling=false;this._isStop=false;if(this.option("sListElement")){this.option("bUseCss3d",false);}
this._setTrans();if(this.bUseHighlight){if(this.isPositionBug){this._elDummyTag=null;}
if(this.isIos){this._aAnchor=null;this._fnDummyFnc=function(){return false;};this._bBlocked=false;}}},_setTrans:function(){if(this.option("bUseCss3d")){this.sTranOpen="3d(";this.sTranEnd=",0)";}else{this.sTranOpen="(";this.sTranEnd=")";}},getCurrentPos:function(){return{nTop:this._nTop,nLeft:this._nLeft};},setLayer:function(el){this._htWElement["wrapper"]=jindo.$Element(el);this._htWElement["wrapper"].css("overflow","hidden");if(this._htWElement["wrapper"].css("position")=="static"){this._htWElement["wrapper"].css("position","relative");}
if(!this.bUseHighlight){this._htWElement["wrapper"].css(this.sCssPrefix+"TapHighlightColor","rgba(0,0,0,0)");}
this.setScroller();},setScroller:function(){this._htWElement["scroller"]=this._htWElement["wrapper"].first();this._htWElement["scroller"].css({"position":"absolute","zIndex":1,"left":0,"top":0});if(this.option("bUseTranslate")||this.option("bUseCss3d")){this._htWElement["scroller"].css(this.sCssPrefix+"TransitionProperty","-webkit-transform").css(this.sCssPrefix+"Transform","translate"+this.sTranOpen+"0,0"+this.sTranEnd);}
if(this.option("bUseTimingFunction")){this._htWElement["scroller"].css(this.sCssPrefix+"TransitionTimingFunction","cubic-bezier(0.33,0.66,0.66,1)");}
if(this.isPositionBug&&this.bUseHighlight&&this.nVersion<3){this._elDummyTag=this._htWElement["scroller"].query("._scroller_dummy_atag_");if(!this._elDummyTag){this._elDummyTag=jindo.$("<a href='javascript:void(0);' style='position:absolute;height:0px;width:0px;' class='_scroller_dummy_atag_'></a>");this._htWElement["scroller"].append(this._elDummyTag);}}},_setWrapperElement:function(el){this._htWElement={};this.setLayer(el);},refresh:function(bNoRepos){if(!this.isActivating()){return;}
if(this.option("nWidth")){this._htWElement["wrapper"].width(parseInt(this.option("nWidth"),10));}
if(this.option("nHeight")){this._htWElement["wrapper"].height(parseInt(this.option("nHeight"),10));}
this.nWrapperW=this._htWElement["wrapper"].width()-parseInt(this._htWElement["wrapper"].css("border-left-width"),10)-parseInt(this._htWElement["wrapper"].css("border-right-width"),10);this.nWrapperH=this._htWElement["wrapper"].height()-parseInt(this._htWElement["wrapper"].css("border-top-width"),10)-parseInt(this._htWElement["wrapper"].css("border-bottom-width"),10);this.nScrollW=this._htWElement["scroller"].width();this.nScrollH=this._htWElement["scroller"].height()-this.option("nOffsetBottom");this.nMaxScrollLeft=this.nWrapperW-this.nScrollW;this.nMaxScrollTop=this.nWrapperH-this.nScrollH;this.nMinScrollTop=-this.option("nOffsetTop");if(this.bUseHighlight&&this.isIos){this._aAnchor=jindo.$$("A",this._htWElement["scroller"].$value());}
this.bUseHScroll=this.option("bUseHScroll")&&(this.nWrapperW<=this.nScrollW);this.bUseVScroll=this.option("bUseVScroll")&&(this.nWrapperH<=this.nScrollH);if(this.bUseHScroll&&!this.bUseVScroll){this._htWElement["scroller"].$value().style["height"]="100%";}
if(!this.bUseHScroll&&this.bUseVScroll){this._htWElement["scroller"].$value().style["width"]="100%";}
this._bUseDynamicScroll=false;if(this.option("sListElement")&&!(this.bUseVScroll&&this.bUseHScroll)){var nRange=this.option("nRatio")*2;if(this.bUseVScroll&&(this.nScrollH>(this.nWrapperH*nRange))){this._createDynamicScrollPlugin("V");}else if(this.bUseHScroll&&(this.nScrollW>(this.nWrapperW*nRange))){this._createDynamicScrollPlugin("H");}}
if(!this.bUseHScroll&&!this.bUseVScroll){this._fixPositionBug();}
if(!bNoRepos){this.restorePos(0);}},_createDynamicScrollPlugin:function(sDirection){if(!this._oDynamicScrollPlugin){this._oDynamicScrollPlugin=new jindo.m.DynamicScrollPlugin(this._htWElement["wrapper"],{nRatio:this.option("nRatio"),sListElement:this.option("sListElement"),sDirection:sDirection});}
this._oDynamicScrollPlugin.refresh(sDirection=="V"?this._nTop:this._nLeft);this.option("bUseTimingFunction",false);this._bUseDynamicScroll=true;},_setPos:function(nLeft,nTop){var sDirection;nLeft=this.bUseHScroll?nLeft:0;nTop=this.bUseVScroll?nTop:0;if(this._bUseDynamicScroll){sDirection=this._checkDirection(nLeft,nTop);}
if(this._fireEvent("beforePosition")){this._isControling=true;this._nLeft=nLeft;this._nTop=nTop;if(this._bUseDynamicScroll){this._oDynamicScrollPlugin.updateListStatus(sDirection,this.bUseVScroll?this._nTop:this._nLeft);}
if(this.option("bUseTranslate")){if(this.bUseHighlight&&this.isPositionBug){var htStyleOffset=this.getStyleOffset(this._htWElement["scroller"]);nLeft-=htStyleOffset.left;nTop-=htStyleOffset.top;}
this._htWElement["scroller"].css(this.sCssPrefix+"Transform","translate"+this.sTranOpen+nLeft+"px, "+nTop+"px"+this.sTranEnd);}else{this._htWElement["scroller"].css({"left":nLeft+"px","top":nTop+"px"});}
this._fireEvent("position");}},_checkDirection:function(nLeft,nTop){var nBeforePos=this.bUseVScroll?this._nTop:this._nLeft,nAfterPos=this.bUseVScroll?nTop:nLeft,sDirection;if(nBeforePos>nAfterPos){sDirection="forward";}else{sDirection="backward";}
return sDirection;},restorePos:function(nDuration){if(!this.bUseHScroll&&!this.bUseVScroll){return;}
var nNewLeft=this.getPosLeft(this._nLeft),nNewTop=this.getPosTop(this._nTop);if(nNewLeft===this._nLeft&&nNewTop===this._nTop){this._isControling=false;this._fireEvent("afterScroll");this._fixPositionBug();return;}else{this.scrollTo(nNewLeft,nNewTop,nDuration);}},_getMomentum:function(nDistance,nSpeed,nMomentum,nSize,nMaxDistUpper,nMaxDistLower){var nDeceleration=this.option("nDeceleration"),nNewDist=nMomentum/nDeceleration,nNewTime=0,nOutsideDist=0;if(nDistance<0&&nNewDist>nMaxDistUpper){nOutsideDist=nSize/(6/(nNewDist/nSpeed*nDeceleration));nMaxDistUpper=nMaxDistUpper+nOutsideDist;nSpeed=nSpeed*nMaxDistUpper/nNewDist;nNewDist=nMaxDistUpper;}else if(nDistance>0&&nNewDist>nMaxDistLower){nOutsideDist=nSize/(6/(nNewDist/nSpeed*nDeceleration));nMaxDistLower=nMaxDistLower+nOutsideDist;nSpeed=nSpeed*nMaxDistLower/nNewDist;nNewDist=nMaxDistLower;}
nNewDist=nNewDist*(nDistance>0?-1:1);nNewTime=nSpeed/nDeceleration;return{nDist:nNewDist,nTime:Math.round(nNewTime)};},_stop:function(){if(this.option("bUseTimingFunction")){jindo.m.detachTransitionEnd(this._htWElement["scroller"].$value(),this._htEvent["TransitionEnd"]);}else{cancelRequestAnimationFrame(this._nAniTimer);}
this._aAni=[];this._isAnimating=false;},scrollTo:function(nLeft,nTop,nDuration){this._stop();nLeft=this.bUseHScroll?nLeft:0;nTop=this.bUseVScroll?nTop:0;this._aAni.push({nLeft:nLeft,nTop:nTop,nDuration:nDuration||0});this._animate();},isMoving:function(){return this._isControling;},_animate:function(){var self=this,oStep;if(this._isAnimating){return;}
if(!this._aAni.length){this.restorePos(300);return;}
do{oStep=this._aAni.shift();if(!oStep){return;}}while(oStep.nLeft==this._nLeft&&oStep.nTop==this._nTop);if(oStep.nDuration==0){if(this.option("bUseTimingFunction")){this._transitionTime(0);}
this._setPos(oStep.nLeft,oStep.nTop);this._animate();}else{this._isAnimating=true;if(this.option("bUseTimingFunction")){this._transitionTime(oStep.nDuration);this._setPos(oStep.nLeft,oStep.nTop);this._isAnimating=false;jindo.m.attachTransitionEnd(this._htWElement["scroller"].$value(),this._htEvent["TransitionEnd"]);}else{var startTime=(new Date()).getTime(),nStartLeft=this._nLeft,nStartTop=this._nTop;(function animate(){var now=(new Date()).getTime(),nEaseOut;if(now>=startTime+oStep.nDuration){self._setPos(oStep.nLeft,oStep.nTop);self._isAnimating=false;self._animate();return;}
now=(now-startTime)/oStep.nDuration-1;nEaseOut=Math.sqrt(1-Math.pow(now,2));self._setPos((oStep.nLeft-nStartLeft)*nEaseOut+nStartLeft,(oStep.nTop-nStartTop)*nEaseOut+nStartTop);if(self._isAnimating){self._nAniTimer=requestAnimationFrame(animate);}})();}}},_transitionTime:function(nDuration){nDuration+='ms';this._htWElement["scroller"].css(this.sCssPrefix+"TransitionDuration",nDuration);this._fireEventSetDuration(nDuration);},_clearAnchorForIos:function(){if(this.isIos&&this._aAnchor&&!this._bBlocked){var aClickAddEvent=null;for(var i=0,nILength=this._aAnchor.length;i<nILength;i++){if(!this._aAnchor[i].___isClear___){if(this._fnDummyFnc!==this._aAnchor[i].onclick){this._aAnchor[i]._onclick=this._aAnchor[i].onclick;}
this._aAnchor[i].onclick=this._fnDummyFnc;this._aAnchor[i].___isClear___=true;aClickAddEvent=this._aAnchor[i].___listeners___||[];for(var j=0,nJLength=aClickAddEvent.length;j<nJLength;j++){___Old__removeEventListener___.call(this._aAnchor[i],"click",aClickAddEvent[j].listener,aClickAddEvent[j].useCapture);}}}
this._bBlocked=true;}},_restoreAnchorForIos:function(){if(this.isIos&&this._aAnchor&&this._bBlocked){var aClickAddEvent=null;for(var i=0,nILength=this._aAnchor.length;i<nILength;i++){if(this._aAnchor[i].___isClear___){if(this._fnDummyFnc!==this._aAnchor[i]._onclick){this._aAnchor[i].onclick=this._aAnchor[i]._onclick;}else{this._aAnchor[i].onclick=null;}
this._aAnchor[i].___isClear___=null;aClickAddEvent=this._aAnchor[i].___listeners___||[];for(var j=0,nJLength=aClickAddEvent.length;j<nJLength;j++){___Old__addEventListener___.call(this._aAnchor[i],"click",aClickAddEvent[j].listener,aClickAddEvent[j].useCapture);}}}
this._bBlocked=false;}},_stopScroll:function(){var htCssOffset=jindo.m.getCssOffset(this._htWElement["scroller"].$value()),htStyleOffset={left:0,top:0},nTop,nLeft;if(this.isPositionBug&&this.bUseHighlight||!this.option("bUseTranslate")){htStyleOffset=this.getStyleOffset(this._htWElement["scroller"]);}
nLeft=htCssOffset.left+htStyleOffset.left;nTop=htCssOffset.top+htStyleOffset.top;if(nLeft!==this._nLeft||nTop!==this._nTop){this._stop();this._isStop=true;this._setPos(this.getPosLeft(nLeft),this.getPosTop(nTop));this._isControling=false;this._fireEvent("afterScroll");this._fixPositionBug();}},getStyleOffset:function(wel){var nLeft=parseInt(wel.css("left"),10),nTop=parseInt(wel.css("top"),10);nLeft=isNaN(nLeft)?0:nLeft;nTop=isNaN(nTop)?0:nTop;return{left:nLeft,top:nTop};},getPosLeft:function(nPos){return(nPos>=0?0:(nPos<=this.nMaxScrollLeft?this.nMaxScrollLeft:nPos));},getPosTop:function(nPos){return(nPos>=this.nMinScrollTop?this.nMinScrollTop:(nPos<=this.nMaxScrollTop?this.nMaxScrollTop:nPos));},_fireEventSetDuration:function(nDuration){this.fireEvent("setDuration",{nDuration:nDuration,bUseHScroll:this.bUseHScroll,bUseVScroll:this.bUseVScroll});},_fireEventbeforeScroll:function(htParam){return this.fireEvent("beforeScroll",htParam);},_fireEventScroll:function(htParam){this.fireEvent("scroll",htParam);},_fireEvent:function(sType){return this.fireEvent(sType,{nLeft:this._nLeft,nTop:this._nTop,nMaxScrollLeft:this.nMaxScrollLeft,nMaxScrollTop:this.nMaxScrollTop});},_fireTouchEvent:function(sType,we){return this.fireEvent(sType,{nLeft:this._nLeft,nTop:this._nTop,nMaxScrollLeft:this.nMaxScrollLeft,nMaxScrollTop:this.nMaxScrollTop,oEvent:we});},_onStart:function(we){this._clearFixPositionBug();if(this._fireTouchEvent("beforeTouchStart",we)){this._clearAnchorForIos();this._isAnimating=false;this._isControling=true;this._isStop=false;if(this.option("bUseTimingFunction")){this._transitionTime(0);}
this._stopScroll();this._fireTouchEvent("touchStart",we);}},_onMove:function(we){var weParent=we.oEvent;if(we.sMoveType===jindo.m.MOVETYPE[0]){if(this.bUseHScroll){if(!this.option("bUseBounce")&&((this._nLeft>=0&&we.nVectorX>0)||(this._nLeft<=this.nMaxScrollLeft&&we.nVectorX<0))){this._forceRestore(we);return;}else{weParent.stop(jindo.$Event.CANCEL_ALL);}}else{return true;}}else if(we.sMoveType===jindo.m.MOVETYPE[1]){if(this.bUseVScroll){if(!this.option("bUseBounce")&&((this._nTop>=this.nMinScrollTop&&we.nVectorY>0)||(this._nTop<=this.nMaxScrollTop&&we.nVectorY<0))){this._forceRestore(we);return;}else{weParent.stop(jindo.$Event.CANCEL_ALL);}}else{return true;}}else if(we.sMoveType===jindo.m.MOVETYPE[2]){weParent.stop(jindo.$Event.CANCEL_ALL);}else{weParent.stop(jindo.$Event.CANCEL_ALL);return true;}
if(this._fireTouchEvent("beforeTouchMove",we)){var nNewLeft,nNewTop;this._clearFixPositionBug();if(this.option("bUseBounce")){nNewLeft=this._nLeft+(this._nLeft>=0||this._nLeft<=this.nMaxScrollLeft?we.nVectorX/2:we.nVectorX);nNewTop=this._nTop+(this._nTop>=this.nMinScrollTop||this._nTop<=this.nMaxScrollTop?we.nVectorY/2:we.nVectorY);if(this.bUseVScroll&&we.nY<=30&&!this.bUseHScroll){this._forceRestore(we);return;}}else{nNewLeft=this.getPosLeft(this._nLeft+we.nVectorX);nNewTop=this.getPosTop(this._nTop+we.nVectorY);}
this._setPos(nNewLeft,nNewTop);this._fireTouchEvent("touchMove",we);}},_onEnd:function(we){if(!this._fireTouchEvent("beforeTouchEnd",we)){return;}
this._clearFixPositionBug();if(we.sMoveType===jindo.m.MOVETYPE[0]||we.sMoveType===jindo.m.MOVETYPE[1]||we.sMoveType===jindo.m.MOVETYPE[2]){this._endForScroll(we);if(this.isIos||this.nVersion<4.1){we.oEvent.stop(jindo.$Event.CANCEL_DEFAULT);}}else{this._isControling=false;if(!this._isStop){if(this.bUseHighlight){this._restoreAnchorForIos();}}}
this._fireTouchEvent("touchEnd",we);},_forceRestore:function(we){we.nMomentumX=we.nMomentumY=null;this._endForScroll(we);this._clearFixPositionBug();},_endForScroll:function(we){var htMomentumX={nDist:0,nTime:0},htMomentumY={nDist:0,nTime:0},htParam={nMomentumX:we.nMomentumX,nMomentumY:we.nMomentumY,nDistanceX:we.nDistanceX,nDistanceY:we.nDistanceY,nLeft:this._nLeft,nTop:this._nTop};if(this.option("bUseMomentum")&&(we.nMomentumX||we.nMomentumY)){if(this.bUseHScroll){htMomentumX=this._getMomentum(-we.nDistanceX,we.nSpeedX,we.nMomentumX,this.nWrapperW,-this._nLeft,-this.nMaxScrollLeft+this._nLeft);}
if(this.bUseVScroll){htMomentumY=this._getMomentum(-we.nDistanceY,we.nSpeedY,we.nMomentumY,this.nWrapperH,-this._nTop,-this.nMaxScrollTop+this._nTop);}
htParam.nNextLeft=this._nLeft+htMomentumX.nDist;htParam.nNextTop=this._nTop+htMomentumY.nDist;htParam.nTime=Math.max(Math.max(htMomentumX.nTime,htMomentumY.nTime),10);if(this._fireEventbeforeScroll(htParam)){if(this.option("bUseBounce")){this.scrollTo(htParam.nNextLeft,htParam.nNextTop,htParam.nTime);}else{this.scrollTo(this.getPosLeft(htParam.nNextLeft),this.getPosTop(htParam.nNextTop),htParam.nTime);}
this._fireEventScroll(htParam);}}else{htParam.nNextLeft=this._nLeft;htParam.nNextTop=this._nTop;htParam.nTime=0;if(this._fireEventbeforeScroll(htParam)){if(this._nLeft!==htParam.nNextLeft||this._nTop!==htParam.nNextTop){this.scrollTo(htParam.nNextLeft,htParam.nNextTop,htParam.nTime);}else{this.restorePos(300);}
this._fireEventScroll(htParam);}}},_onTransitionEnd:function(we){jindo.m.detachTransitionEnd(this._htWElement["scroller"].$value(),this._htEvent["TransitionEnd"]);this._animate();},_onDocumentStart:function(we){if(this._htWElement["wrapper"].visible()){if(this._htWElement["wrapper"].isChildOf(we.element)){return true;}else{this._stopScroll();}}},_onActivate:function(){if(!this._oTouch){this._oTouch=new jindo.m.Touch(this._htWElement["wrapper"].$value(),{nMoveThreshold:0,nMomentumDuration:(jindo.m.getDeviceInfo().android?500:200),nTapThreshold:1,nSlopeThreshold:5});}else{this._oTouch.activate();}
this._attachEvent();this.refresh();},_onDeactivate:function(){this._detachEvent();this._oTouch.deactivate();},_attachEvent:function(){this._htEvent={};this._htEvent["touchStart"]=jindo.$Fn(this._onStart,this).bind();this._htEvent["touchMove"]=jindo.$Fn(this._onMove,this).bind();this._htEvent["touchEnd"]=jindo.$Fn(this._onEnd,this).bind();this._htEvent["TransitionEnd"]=jindo.$Fn(this._onTransitionEnd,this).bind();this._htEvent["document"]=jindo.$Fn(this._onDocumentStart,this).attach(document,"touchstart");this._oTouch.attach({touchStart:this._htEvent["touchStart"],touchMove:this._htEvent["touchMove"],touchEnd:this._htEvent["touchEnd"]});},_fixPositionBug:function(){if(this.isPositionBug&&this.bUseHighlight&&this.option("bUseTranslate")){var self=this;this._clearFixPositionBug();this._nFixePositionBugTimer=setTimeout(function(){if(self._htWElement&&self._htWElement["scroller"]){self.makeStylePos(self._htWElement["scroller"]);if(self.nVersion<3){self._elDummyTag.focus();}}},200);}},makeStylePos:function(wel){var ele=wel.$value();var htCssOffset=jindo.m.getCssOffset(ele);var htScrollOffset=wel.offset();if(this.nVersion>=4){ele.style[this.sCssPrefix+"Transform"]="translate"+this.sTranOpen+"0px, 0px"+this.sTranEnd;}else{ele.style[this.sCssPrefix+"Transform"]=null;}
ele.style[this.sCssPrefix+"TransitionDuration"]=null;wel.offset(htCssOffset.top+htScrollOffset.top,htCssOffset.left+htScrollOffset.left);},_clearFixPositionBug:function(){if(this.isPositionBug&&this.bUseHighlight){clearTimeout(this._nFixePositionBugTimer);this._nFixePositionBugTimer=-1;}},_detachEvent:function(){jindo.m.detachTransitionEnd(this._htWElement["scroller"].$value(),this._htEvent["TransitionEnd"]);this._htEvent["document"].detach(document,"touchstart");this._oTouch.detachAll();if(this._elDummyTag){this._htWElement["scroller"].remove(this._elDummyTag);}},destroy:function(){this.deactivate();for(var p in this._htWElement){this._htWElement[p]=null;}
this._htWElement=null;this._oTouch.destroy();delete this._oTouch;}}).extend(jindo.UIComponent);jindo.m.Touch=jindo.$Class({$init:function(sId,htUserOption){this._el=jindo.$(sId);var htDefaultOption={nMomentumDuration:350,nMoveThreshold:7,nSlopeThreshold:25,nLongTapDuration:1000,nDoubleTapDuration:400,nTapThreshold:6,nPinchThreshold:0.1,nRotateThreshold:5,bActivateOnload:true};this.option(htDefaultOption);this.option(htUserOption||{});this._initVariable();this._setSlope();if(this.option("bActivateOnload")){this.activate();}},_initVariable:function(){this._hasTouchEvent='ontouchstart'in window;this._radianToDegree=180/Math.PI;this._htMoveInfo={nStartX:0,nStartY:0,nBeforeX:0,nBeforeY:0,nStartTime:0,nBeforeTime:0,nStartDistance:0,nBeforeDistance:0,nStartAngle:0,nLastAngle:0};this.bStart=false;this.bMove=false;this.nMoveType=-1;this.htEndInfo={};this._nVSlope=0;this._nHSlope=0;this.bSetSlope=false;},_attachEvents:function(){this._htEvent={};var bTouch=this._hasTouchEvent;this._htEvent[bTouch?'touchstart':'mousedown']={ref:jindo.$Fn(this._onStart,this).attach(this._el,(bTouch?'touchstart':'mousedown')),el:this._el};this._htEvent[bTouch?'touchmove':'mousemove']={ref:jindo.$Fn(this._onMove,this).attach(this._el,(bTouch?'touchmove':'mousemove')),el:this._el};this._htEvent[bTouch?'touchend':'mouseup']={ref:jindo.$Fn(this._onEnd,this).attach(this._el,(bTouch?'touchend':'mouseup')),el:this._el};this._htEvent["rotate"]=jindo.$Fn(this._onResize,this).bind();jindo.m.bindRotate(this._htEvent["rotate"]);if(bTouch){this._htEvent['touchcancel']={ref:jindo.$Fn(this._onCancel,this).attach(this._el,'touchcancel'),el:this._el};}},_detachEvents:function(){for(var p in this._htEvent){var htTargetEvent=this._htEvent[p];if(htTargetEvent.ref){htTargetEvent.ref.detach(htTargetEvent.el,p);}}
jindo.m.unbindRotate(this._htEvent["rotate"]);this._htEvent=null;},_onCancel:function(oEvent){this._onEnd(oEvent);},_onStart:function(oEvent){this._resetTouchInfo();var htInfo=this._getTouchInfo(oEvent);var htParam={element:htInfo[0].el,nX:htInfo[0].nX,nY:htInfo[0].nY,oEvent:oEvent};if(!this._fireCustomEvent('touchStart',htParam)){return;}
this.bStart=true;this._htMoveInfo.nStartX=htInfo[0].nX;this._htMoveInfo.nBeforeX=htInfo[0].nX;this._htMoveInfo.nStartY=htInfo[0].nY;this._htMoveInfo.nBeforeY=htInfo[0].nY;this._htMoveInfo.nStartTime=htInfo[0].nTime;this._htMoveInfo.aStartInfo=htInfo;this._startLongTapTimer(htInfo,oEvent);},_onMove:function(oEvent){if(!this.bStart){return;}
this.bMove=true;var htInfo=this._getTouchInfo(oEvent);var htParam=this._getCustomEventParam(htInfo,false);if(htInfo.length===1){if(this.nMoveType<0||this.nMoveType==3||this.nMoveType==4){this.nMoveType=this._getMoveType(htInfo);}}else{if(this.nMoveType!==8){this.nMoveType=this._getMoveType(htInfo);}}
htParam=this._getCustomEventParam(htInfo,false);if((typeof this._nLongTapTimer!='undefined')&&this.nMoveType!=3){this._deleteLongTapTimer();}
htParam.oEvent=oEvent;var nDis=0;if(this.nMoveType==0){nDis=Math.abs(htParam.nVectorX);}else if(this.nMoveType==1){nDis=Math.abs(htParam.nVectorY);}else{nDis=Math.abs(htParam.nVectorX)+Math.abs(htParam.nVectorY);}
if(nDis<this.option('nMoveThreshold')){return;}
if(!this.fireEvent('touchMove',htParam)){this.bStart=false;return;}
this._htMoveInfo.nBeforeX=htInfo[0].nX;this._htMoveInfo.nBeforeY=htInfo[0].nY;this._htMoveInfo.nBeforeTime=htInfo[0].nTime;},_onEnd:function(oEvent){if(!this.bStart){return;}
var self=this;this._deleteLongTapTimer();if(!this.bMove&&(this.nMoveType!=4)){this.nMoveType=3;}
if(this.nMoveType<0){return;}
var htInfo=this._getTouchInfo(oEvent);if(this._isDblTap(htInfo[0].nX,htInfo[0].nY,htInfo[0].nTime)){clearTimeout(this._nTapTimer);delete this._nTapTimer;this.nMoveType=5;}
var htParam=this._getCustomEventParam(htInfo,true);htParam.oEvent=oEvent;var sMoveType=htParam.sMoveType;if((typeof this._htEventHandler[jindo.m.MOVETYPE[5]]!='undefined'&&(this._htEventHandler[jindo.m.MOVETYPE[5]].length>0))&&(this.nMoveType==3)){this._nTapTimer=setTimeout(function(){self.fireEvent('touchEnd',htParam);self._fireCustomEvent(sMoveType,htParam);delete self._nTapTimer;},this.option('nDoubleTapDuration'));}else{this.fireEvent('touchEnd',htParam);if(this.nMoveType!=4){if(this.nMoveType===8){htParam.sMoveType=jindo.m.MOVETYPE[6];this._fireCustomEvent(jindo.m.MOVETYPE[6],htParam);htParam.sMoveType=jindo.m.MOVETYPE[7];this._fireCustomEvent(jindo.m.MOVETYPE[7],htParam);}else{setTimeout(function(){self._fireCustomEvent(sMoveType,htParam);},0);}}}
this._updateTouchEndInfo(htInfo);this._resetTouchInfo();},_fireCustomEvent:function(sEvent,htOption){return this.fireEvent(sEvent,htOption);},_getCustomEventParam:function(htTouchInfo,bTouchEnd){var sMoveType=jindo.m.MOVETYPE[this.nMoveType];var nDuration=htTouchInfo[0].nTime-this._htMoveInfo.nStartTime;var nVectorX=nVectorY=nMomentumX=nMomentumY=nSpeedX=nSpeedY=nDisX=nDisY=0;nDisX=(this.nMoveType===1)?0:htTouchInfo[0].nX-this._htMoveInfo.nStartX;nDisY=(this.nMoveType===0)?0:htTouchInfo[0].nY-this._htMoveInfo.nStartY;nVectorX=htTouchInfo[0].nX-this._htMoveInfo.nBeforeX;nVectorY=htTouchInfo[0].nY-this._htMoveInfo.nBeforeY;if(bTouchEnd&&(this.nMoveType==0||this.nMoveType==1||this.nMoveType==2)){if(nDuration<=this.option('nMomentumDuration')){nSpeedX=Math.abs(nDisX)/nDuration;nMomentumX=(nSpeedX*nSpeedX)/2;nSpeedY=Math.abs(nDisY)/nDuration;nMomentumY=(nSpeedY*nSpeedY)/2;}}
var htParam={element:htTouchInfo[0].el,nX:htTouchInfo[0].nX,nY:htTouchInfo[0].nY,nVectorX:nVectorX,nVectorY:nVectorY,nDistanceX:nDisX,nDistanceY:nDisY,sMoveType:sMoveType,nStartX:this._htMoveInfo.nStartX,nStartY:this._htMoveInfo.nStartY,nStartTimeStamp:this._htMoveInfo.nStartTime};if((htTouchInfo.length)>1||(this.nMoveType>=6)){htParam.nScale=this._getScale(htTouchInfo);htParam.nRotation=this._getRotation(htTouchInfo);if(htParam.nScale===null){htParam.nScale=this._htMoveInfo.nBeforeScale;}
if(htParam.nRotation===null){htParam.nRotation=this._htMoveInfo.nBeforeRotation;}}
if(htTouchInfo.length>=1){var aX=[];var aY=[];var aElement=[];for(var i=0,nLen=htTouchInfo.length;i<nLen;i++){aX.push(htTouchInfo[i].nX);aY.push(htTouchInfo[i].nY);aElement.push(htTouchInfo[i].el);}
htParam.aX=aX;htParam.aY=aY;htParam.aElement=aElement;}
if(bTouchEnd){htParam.nMomentumX=nMomentumX;htParam.nMomentumY=nMomentumY;htParam.nSpeedX=nSpeedX;htParam.nSpeedY=nSpeedY;htParam.nDuration=nDuration;}
return htParam;},_updateTouchEndInfo:function(htInfo){this.htEndInfo={element:htInfo[0].el,time:htInfo[0].nTime,movetype:this.nMoveType,nX:htInfo[0].nX,nY:htInfo[0].nY};},_deleteLongTapTimer:function(){if(typeof this._nLongTapTimer!='undefined'){clearTimeout(this._nLongTapTimer);delete this._nLongTapTimer;}},_startLongTapTimer:function(htInfo,oEvent){var self=this;if((typeof this._htEventHandler[jindo.m.MOVETYPE[4]]!='undefined')&&(this._htEventHandler[jindo.m.MOVETYPE[4]].length>0)){self._nLongTapTimer=setTimeout(function(){self.fireEvent('longTap',{element:htInfo[0].el,oEvent:oEvent,nX:htInfo[0].nX,nY:htInfo[0].nY});delete self._nLongTapTimer;self.nMoveType=4;},self.option('nLongTapDuration'));}},_onResize:function(){this._setSlope();},_isDblTap:function(nX,nY,nTime){if((typeof this._nTapTimer!='undefined')&&this.nMoveType==3){var nGap=this.option('nTapThreshold');if((Math.abs(this.htEndInfo.nX-nX)<=nGap)&&(Math.abs(this.htEndInfo.nY-nY)<=nGap)){return true;}}
return false;},_setSlope:function(){if(!this.bSetSlope){this._nHSlope=((window.innerHeight/2)/window.innerWidth).toFixed(2)*1;this._nVSlope=(window.innerHeight/(window.innerWidth/2)).toFixed(2)*1;}},setSlope:function(nVSlope,nHSlope){this._nHSlope=nHSlope;this._nVSlope=nVSlope;this.bSetSlope=true;},getSlope:function(){return{nVSlope:this._nVSlope,nHSlope:this._nHSlope}},_resetTouchInfo:function(){for(var x in this._htMoveInfo){this._htMoveInfo[x]=0;}
this._deleteLongTapTimer();this.bStart=false;this.bMove=false;this.nMoveType=-1;},_getMoveTypeBySingle:function(x,y){var nType=this.nMoveType;var nX=Math.abs(this._htMoveInfo.nStartX-x);var nY=Math.abs(this._htMoveInfo.nStartY-y);var nDis=nX+nY;var nGap=this.option('nTapThreshold');if((nX<=nGap)&&(nY<=nGap)){nType=3;}else{nType=-1;}
if(this.option('nSlopeThreshold')<=nDis){var nSlope=parseFloat((nY/nX).toFixed(2),10);if((this._nHSlope===-1)&&(this._nVSlope===-1)){nType=2;}else{if(nSlope<=this._nHSlope){nType=0;}else if(nSlope>=this._nVSlope){nType=1;}else{nType=2;}}}
return nType;},_getMoveTypeByMulti:function(aPos){var nType=-1;if((this.nMoveType===6)||Math.abs(1-this._htMoveInfo.nBeforeScale)>=this.option('nPinchThreshold')){nType=6;}
if((this.nMoveType===7)||Math.abs(0-this._htMoveInfo.nBeforeRotation)>=this.option('nRotateThreshold')){if(nType===6){nType=8;}else{nType=7;}}
if(nType===-1){return this.nMoveType;}
return nType;},_getScale:function(aPos){var nScale=-1;var nDistance=this._getDistance(aPos);if(nDistance<=0){return null;}
if(this._htMoveInfo.nStartDistance===0){nScale=1;this._htMoveInfo.nStartDistance=nDistance;}else{nScale=nDistance/this._htMoveInfo.nStartDistance;}
this._htMoveInfo.nBeforeScale=nScale;return nScale;},_getRotation:function(aPos){var nRotation=-1;var nAngle=this._getAngle(aPos);if(nAngle===null){return null;}
if(this._htMoveInfo.nStartAngle===0){this._htMoveInfo.nStartAngle=nAngle;nRotation=0;}else{nRotation=nAngle-this._htMoveInfo.nStartAngle;}
this._htMoveInfo.nLastAngle=nAngle;this._htMoveInfo.nBeforeRotation=nRotation;return nRotation;},_getMoveType:function(aPos){var nType=this.nMoveType;if(aPos.length===1){nType=this._getMoveTypeBySingle(aPos[0].nX,aPos[0].nY);}else if(aPos.length===2){nType=this._getMoveTypeByMulti(aPos);}
return nType;},_getDistance:function(aPos){if(aPos.length===1){return-1;}
return Math.sqrt(Math.pow(Math.abs(aPos[0].nX-aPos[1].nX),2)+
Math.pow(Math.abs(aPos[0].nY-aPos[1].nY),2));},_getAngle:function(aPos){if(aPos.length===1){return null;}
var deltaX=aPos[0].nX-aPos[1].nX,deltaY=aPos[0].nY-aPos[1].nY;var nAngle=Math.atan2(deltaY,deltaX)*this._radianToDegree;if(this._htMoveInfo.nLastAngle!==null){var nDiff=Math.abs(this._htMoveInfo.nLastAngle-nAngle);var nNext=nAngle+360;var nPrev=nAngle-360;if(Math.abs(nNext-this._htMoveInfo.nLastAngle)<nDiff){nAngle=nNext;}else if(Math.abs(nPrev-this._htMoveInfo.nLastAngle)<nDiff){nAngle=nPrev;}}
return nAngle;},_getTouchInfo:function(oEvent){var aReturn=[];var nTime=oEvent.$value().timeStamp;if(this._hasTouchEvent){var oTouch=oEvent.$value().changedTouches;for(var i=0,nLen=oTouch.length;i<nLen;i++){aReturn.push({el:jindo.m.getNodeElement(oTouch[i].target),nX:oTouch[i].pageX,nY:oTouch[i].pageY,nTime:nTime});}}else{aReturn.push({el:oEvent.element,nX:oEvent.pos().pageX,nY:oEvent.pos().pageY,nTime:nTime});}
return aReturn;},getBaseElement:function(el){return this._el;},_onDeactivate:function(){this._detachEvents();},_onActivate:function(){this._attachEvents();},destroy:function(){this.deactivate();this._el=null;for(var p in this._htMoveInfo){this._htMoveInfo[p]=null;}
this._htMoveInfo=null;for(var p in this.htEndInfo){this.htEndInfo[p]=null;}
this.htEndInfo=null;this.bStart=null;this.bMove=null;this.nMoveType=null;this._nVSlope=null;this._nHSlope=null;this.bSetSlope=null;}}).extend(jindo.UIComponent);jindo.m.DynamicScrollPlugin=jindo.$Class({$init:function(el,htUserOption){this.option({nRatio:1.5,sListElement:"li",sDirection:"V"});this.option(htUserOption||{});this._initVar(el);},_initVar:function(el){this._wel=jindo.$Element(el);this._aListElement=null;this._nStartIdx=-1;this._nEndIdx=-1;this._nRatio=parseInt(this.option("nRatio"),10);this._nPos=-1;this._nSize=-1;this._sDirection=this.option("sDirection");},refresh:function(nPos){var aListElement=this._wel.queryAll(this.option("sListElement"));if(!aListElement){return;}
this._aListElement=[];for(var i=0,nLength=aListElement.length;i<nLength;i++){wel=aListElement[i];this._aListElement.push({el:wel.$value(),wel:wel,htRange:this._getElementPos(wel),sDisplay:wel.css("display"),sPosition:wel.css("position")});}
this._nPos=nPos||0;this._nSize=this._sDirection=="V"?this._wel.height():this._wel.width();this._covertPositionType();},_covertPositionType:function(){var nStartPos=this._getStartBoundary(),nEndPos=this._getEndBoundary();for(var i=0,ht,nLength=this._aListElement.length;i<nLength;i++){ht=this._aListElement[i];if(this._sDirection=="V"){ht.wel.css({"top":ht.htRange.nStartPos+"px","width":"100%"});}else{ht.wel.css({"left":ht.htRange.nStartPos+"px","height":"100%"});}
ht.wel.css("position","absolute");if(ht.htRange.nStartPos<=-nStartPos){this._nStartIdx=i;}else if(ht.htRange.nEndPos<=-nEndPos){ht.el.style.display=ht.sDisplay;this._nEndIdx=i;}else{ht.el.style.display="none";}}},updateListStatus:function(sDirection,nPos){if(!this._aListElement){return;}
this._nPos=nPos;var nStartPos=this._getStartBoundary(),nEndPos=this._getEndBoundary(),nLength=this._aListElement.length,ht,i,nWelPos;if(sDirection=="forward"){for(i=this._nStartIdx+1;i<nLength;i++){ht=this._aListElement[i];nWelPos=ht.htRange.nEndPos;if(nWelPos<-nStartPos){ht.el.style.display="none";this._nStartIdx=i;}else{break;}}
for(i=this._nEndIdx;i<nLength;i++){ht=this._aListElement[i];nWelPos=ht.htRange.nStartPos;if(nWelPos<-nEndPos){ht.el.style.display=ht.sDisplay;this._nEndIdx++;}else{break;}}}else if(sDirection=="backward"){for(i=this._nEndIdx-1;i>=0;i--){ht=this._aListElement[i];nWelPos=ht.htRange.nStartPos;if(nWelPos<-nEndPos){break;}else{ht.el.style.display="none";this._nEndIdx--;}}
for(i=this._nStartIdx;i>=0;i--){ht=this._aListElement[i];nWelPos=ht.htRange.nEndPos;if(nWelPos<-nStartPos){break;}else{ht.el.style.display=ht.sDisplay;this._nStartIdx--;}}}},_getStartBoundary:function(){return this._nPos+(this._nSize*this._nRatio);},_getEndBoundary:function(){return this._nPos-this._nSize-(this._nSize*this._nRatio);},_getElementPos:function(wel){var nStartPos,nEndPos;if(this._sDirection=="V"){nStartPos=wel.offset().top-this._wel.offset().top;nEndPos=nStartPos+wel.height();}else{nStartPos=wel.offset().left-this._wel.offset().left;nEndPos=nStartPos+wel.width();}
return{nStartPos:nStartPos,nEndPos:nEndPos};}}).extend(jindo.Component);jindo.m.Scroll=jindo.$Class({$init:function(el,htUserOption){this.option({bActivateOnload:true,bUseScrollbar:true,bUseFixedScrollbar:false,sScrollbarBorder:"1px solid white",sScrollbarColor:"#8e8e8e",bUsePullDown:false,bUsePullUp:false,sClassPrefix:"scroll_",bUseVScroll:true,bUseHScroll:false,bUseBounce:true,fnPullDownIdle:null,fnPullDownBeforeUpdate:null,fnPullDownUpdating:null,fnPullUpIdle:null,fnPullUpBeforeUpdate:null,fnPullUpUpdating:null,nOffsetTop:0,nOffsetBottom:0,bAutoResize:false});this.option(htUserOption||{});this._initVar();this._setWrapperElement(el);this._InitPullUpdateFunc();if(this.option("bActivateOnload")){this.activate();}},_initVar:function(){this._oCore=null;this._isPullDown=false;this._isPullUp=false;this._isUpdating=false;this._nOrgMaxScrollTop=null;this._nPropHScroll=0;this._nPropVScroll=0;this._htWElement={};},_setWrapperElement:function(el){this._htWElement["wrapper"]=jindo.$Element(el);this._htWElement["pullDown"]=jindo.$Element(this._htWElement["wrapper"].query("."+this.option("sClassPrefix")+"pullDown"));this._htWElement["pullUp"]=jindo.$Element(this._htWElement["wrapper"].query("."+this.option("sClassPrefix")+"pullUp"));},_InitPullUpdateFunc:function(){if(this.option("bUsePullDown")===true){if(!this.option("fnPullDownIdle")){this.option("fnPullDownIdle",function(wel){wel.html("업데이트하시려면 아래로 내려주세요");});}
if(!this.option("fnPullDownBeforeUpdate")){this.option("fnPullDownBeforeUpdate",function(wel){wel.html("업데이트 합니다");});}
if(!this.option("fnPullDownUpdating")){this.option("fnPullDownUpdating",function(wel){wel.html("업데이트 중입니다...");});}}
if(this.option("bUsePullUp")===true){if(!this.option("fnPullUpIdle")){this.option("fnPullUpIdle",function(wel){wel.html("더 보시려면 위로 올려주세요");});}
if(!this.option("fnPullUpBeforeUpdate")){this.option("fnPullUpBeforeUpdate",function(wel){wel.html("로드 합니다");});}
if(!this.option("fnPullUpUpdating")){this.option("fnPullUpUpdating",function(wel){wel.html("로드 중...");});}}},_onActivate:function(){if(this._oCore){this._oCore.activate();}
this.refresh();this._attachEvent();},setUsePullDown:function(bUse){this.option("bUsePullDown",bUse);this._refreshPullStatus();},setUsePullUp:function(bUse){this.option("bUsePullUp",bUse);this._refreshPullStatus();},width:function(nValue){if(nValue){this.option("nWidth",nValue);this.refresh();}else{if(this.option("nWidth")){return parseInt(this.option("nWidth"),10);}else{return this._htWElement["wrapper"].width();}}},height:function(nValue){if(nValue){this.option("nHeight",nValue);this.refresh();}else{if(this.option("nHeight")){return parseInt(this.option("nHeight"),10);}else{return this._htWElement["wrapper"].height();}}},_refreshPullStatus:function(){this._isUpdating=false;this._nOrgMaxScrollTop=null;this._isPullDown=this.option("bUsePullDown")&&this.option("bUseVScroll")&&!this.option("bUseHScroll")&&this.option("bUseBounce")&&(this._htWElement["pullDown"]!==null);this._isPullUp=this.option("bUsePullUp")&&this.option("bUseVScroll")&&!this.option("bUseHScroll")&&this.option("bUseBounce")&&(this._htWElement["pullUp"]!==null);if(this._isPullDown&&this.option("fnPullDownIdle")){this._htWElement["pullDown"]._isReady_=false;this._htWElement["pullDown"].show();this.option("fnPullDownIdle")(this._htWElement["pullDown"]);}
if(this._isPullUp&&this.option("fnPullUpIdle")){this._htWElement["pullUp"]._isReady_=false;this._htWElement["pullUp"].show();this.option("fnPullUpIdle")(this._htWElement["pullUp"]);}},refresh:function(){if(!this.isActivating()){return;}
this._refreshPullStatus();if(this._oCore){this._oCore.option({nOffsetTop:(this._isPullDown?this._htWElement["pullDown"].height():0)-this.option("nOffsetTop"),nOffsetBottom:(this._isPullUp?this._htWElement["pullUp"].height():0)-this.option("nOffsetBottom"),nWidth:this.option("nWidth"),nHeight:this.option("nHeight")});this._oCore.refresh();}else{var htOption=this.option();var htCloneOption={};for(var p in htOption){htCloneOption[p]=htOption[p];}
htCloneOption.bActivateOnload=true;htCloneOption.nOffsetTop=(this._isPullDown?this._htWElement["pullDown"].height():0)-this.option("nOffsetTop");htCloneOption.nOffsetBottom=(this._isPullUp?this._htWElement["pullUp"].height():0)-this.option("nOffsetBottom");this._oCore=new jindo.m.CoreScroll(this._htWElement["wrapper"],htCloneOption);}
if(this.option("bUseScrollbar")){this._refreshScroll("V");this._refreshScroll("H");}
if(!this.hasVScroll()){if(this._htWElement["pullDown"]!==null){this._htWElement["pullDown"].hide();}
if(this._htWElement["pullUp"]!==null){this._htWElement["pullUp"].hide();}}},scrollTo:function(nLeft,nTop,nDuration){nDuration=nDuration||0;nLeft=-Math.abs(nLeft);nTop=-Math.abs(nTop);nTop+=this.getTop();this._oCore.scrollTo((nLeft>=this.getLeft()?this.getLeft():(nLeft<=this.getRight()?this.getRight():nLeft)),(nTop>=this.getTop()?this.getTop():(nTop<=this.getBottom()?this.getBottom():nTop)),nDuration);},getRight:function(){return this._oCore.nMaxScrollLeft;},getLeft:function(){return 0;},getBottom:function(){return this._oCore.nMaxScrollTop;},getTop:function(){return this._oCore.nMinScrollTop;},getCurrentPos:function(){return this._oCore.getCurrentPos();},hasHScroll:function(){return this._oCore.bUseHScroll;},hasVScroll:function(){return this._oCore.bUseVScroll;},_onDeactivate:function(){this._detachEvent();this._oCore.deactivate();},_attachEvent:function(){this._htEvent={};this._oCore.attach({beforeTouchStart:jindo.$Fn(this._onBeforeTouchStart,this).bind(),touchStart:jindo.$Fn(this._onTouchStart,this).bind(),beforeTouchMove:jindo.$Fn(this._onBeforeTouchMove,this).bind(),touchMove:jindo.$Fn(this._onTouchMove,this).bind(),beforeTouchEnd:jindo.$Fn(this._onBeforeTouchEnd,this).bind(),touchEnd:jindo.$Fn(this._onTouchEnd,this).bind(),beforePosition:jindo.$Fn(this._onBeforePosition,this).bind(),position:jindo.$Fn(this._onPosition,this).bind(),setDuration:jindo.$Fn(this._onSetDuration,this).bind(),afterScroll:jindo.$Fn(this._onAfterScroll,this).bind()});if(this.option("bAutoResize")){this._htEvent["rotate"]=jindo.$Fn(this._onRotate,this).bind();jindo.m.bindRotate(this._htEvent["rotate"]);}},_onRotate:function(we){this.refresh();},_onSetDuration:function(we){if(this.option("bUseScrollbar")){if(we.bUseHScroll&&this._htWElement["HscrollbarIndicator"]){this._htWElement["HscrollbarIndicator"].css(this._oCore.sCssPrefix+"TransitionDuration",we.nDuration);}
if(we.bUseVScroll&&this._htWElement["VscrollbarIndicator"]){this._htWElement["VscrollbarIndicator"].css(this._oCore.sCssPrefix+"TransitionDuration",we.nDuration);}}},_onBeforeTouchStart:function(we){if(!this.fireEvent("beforeTouchStart",we)){we.stop();}},_onTouchStart:function(we){this.fireEvent("touchStart",we);},_onBeforeTouchMove:function(we){if(!this.fireEvent("beforeTouchMove",we)){we.stop();}},_onTouchMove:function(we){if(this._isPullDown||this._isPullUp){this._touchMoveForUpdate(we);}
this.fireEvent("touchMove",we);},_onBeforeTouchEnd:function(we){if(!this.fireEvent("beforeTouchEnd",we)){we.stop();}},_onTouchEnd:function(we){if(this._isPullDown&&this._htWElement["pullDown"]._isReady_){this._pullUploading(this._htWElement["pullDown"],false);}
if(this._isPullUp&&this._htWElement["pullUp"]._isReady_){this._pullUploading(this._htWElement["pullUp"],true);}
this.fireEvent("touchEnd",we);},_onBeforePosition:function(we){if(!this.fireEvent("beforePosition",we)){we.stop();}},_onPosition:function(we){if(this.option("bUseScrollbar")){this._setScrollBarPos("V",we.nTop);this._setScrollBarPos("H",we.nLeft);}
this.fireEvent("position",we);},_onAfterScroll:function(we){if(this.option("bUseScrollbar")&&!this.option("bUseFixedScrollbar")){this._hideScrollBar("H");this._hideScrollBar("V");}
this.fireEvent("afterScroll",we);},_hideScrollBar:function(sDirection){var wel=this._htWElement[sDirection+"scrollbar"],bUseScroll=(sDirection==="H"?this._oCore.bUseHScroll:this._oCore.bUseVScroll);if(bUseScroll&&wel){if(this._oCore.isPositionBug&&this._oCore.bUseHighlight){this._oCore.makeStylePos(this._htWElement[sDirection+"scrollbarIndicator"]);}
wel.hide();wel.css("left",wel.css("left")+"px");}},_fireEventPullDown:function(){if(!this._htWElement){return;}
this.fireEvent("pullDown",{welElement:this._htWElement["pullDown"],oScroll:this});},_fireEventPullUp:function(){if(!this._htWElement){return;}
this.fireEvent("pullUp",{welElement:this._htWElement["pullUp"],oScroll:this});},_pullUploading:function(wel,isUp){var fn=isUp?this.option("fnPullUpUpdating"):this.option("fnPullDownUpdating");var self=this;this._isUpdating=true;wel._isReady_=false;if(fn){setTimeout(function(){fn(wel);if(isUp){self._fireEventPullUp();}else{self._fireEventPullDown();}},0);}},_touchMoveForUpdate:function(we){if(this._isUpdating){return;}
var nTopMargin=this._oCore.option("nOffsetTop");var nBottomMargin=this._oCore.option("nOffsetBottom");we.nMaxScrollTop=this._nOrgMaxScrollTop?this._nOrgMaxScrollTop:we.nMaxScrollTop;if(this._isPullDown){if(this._htWElement["pullDown"]._isReady_){if(nTopMargin>we.nTop){this._htWElement["pullDown"]._isReady_=false;if(this.option("fnPullDownIdle")){this.option("fnPullDownIdle")(this._htWElement["pullDown"]);this._oCore.nMinScrollTop=-nTopMargin;}}}else{if(we.nTop>nTopMargin){this._htWElement["pullDown"]._isReady_=true;if(this.option("fnPullDownBeforeUpdate")){this.option("fnPullDownBeforeUpdate")(this._htWElement["pullDown"]);this._oCore.nMinScrollTop=0;}}}}
if(this._isPullUp){if(this._htWElement["pullUp"]._isReady_){if(we.nTop>=(we.nMaxScrollTop-nBottomMargin)){this._htWElement["pullUp"]._isReady_=false;if(this.option("fnPullUpIdle")){this.option("fnPullUpIdle")(this._htWElement["pullUp"]);this._oCore.nMaxScrollTop=we.nMaxScrollTop;}}}else{if(we.nTop<(we.nMaxScrollTop-nBottomMargin)){this._htWElement["pullUp"]._isReady_=true;if(this.option("fnPullUpBeforeUpdate")){this.option("fnPullUpBeforeUpdate")(this._htWElement["pullUp"]);this._nOrgMaxScrollTop=we.nMaxScrollTop;this._oCore.nMaxScrollTop=we.nMaxScrollTop-nBottomMargin;}}}}},isMoving:function(){return this._oCore.isMoving();},_detachEvent:function(){this._oCore.detachAll();if(this.option("bAutoResize")){jindo.m.unbindRotate(this._htEvent["rotate"]);}
this._htEvent=null;},_createScroll:function(sDirection){if(!(sDirection==="H"?this._oCore.bUseHScroll:this._oCore.bUseVScroll)){return;}
var welScrollbar=this._htWElement[sDirection+"scrollbar"],welScrollbarIndicator=this._htWElement[sDirection+"scrollbarIndicator"],welWrapper=this._htWElement["wrapper"];if(welScrollbar){welWrapper.remove(welScrollbar);this._htWElement[sDirection+"scrollbar"]=this._htWElement[sDirection+"scrollbarIndicator"]=null;}
welScrollbar=this._createScrollbar(sDirection);welScrollbarIndicator=this._createScrollbarIndicator(sDirection);this._htWElement[sDirection+"scrollbar"]=welScrollbar;this._htWElement[sDirection+"scrollbarIndicator"]=welScrollbarIndicator;welScrollbar.append(welScrollbarIndicator);welWrapper.append(welScrollbar);this._refreshScroll(sDirection);},_refreshScroll:function(sDirection){if(sDirection==="H"){if(!this._oCore.bUseHScroll||this._oCore.nWrapperW==this._oCore.nScrollW){return;}}else{if(!this._oCore.bUseVScroll||this._oCore.nWrapperH==this._oCore.nScrollH){return;}}
if(!this._htWElement[sDirection+"scrollbar"]){this._createScroll(sDirection);}
var welScrollbar=this._htWElement[sDirection+"scrollbar"],welScrollbarIndicator=this._htWElement[sDirection+"scrollbarIndicator"],nSize=0;if(sDirection==="H"){nSize=Math.max(Math.round(Math.pow(this._oCore.nWrapperW,2)/this._oCore.nScrollW),8);this._nPropHScroll=(this._oCore.nWrapperW-nSize)/this._oCore.nMaxScrollLeft;welScrollbar.width(this._oCore.nWrapperW);welScrollbarIndicator.width(isNaN(nSize)?0:nSize);}else{nSize=Math.max(Math.round(Math.pow(this._oCore.nWrapperH,2)/this._oCore.nScrollH),8);this._nPropVScroll=(this._oCore.nWrapperH-nSize)/this._oCore.nMaxScrollTop;welScrollbar.height(this._oCore.nWrapperH);welScrollbarIndicator.height(isNaN(nSize)?0:nSize);}},_createScrollbar:function(sDirection){var welScrollbar=jindo.$Element("<div>");welScrollbar.css({"position":"absolute","zIndex":100,"bottom":(sDirection==="H"?"1px":(this._oCore.bUseHScroll?'7':'2')+"px"),"right":(sDirection==="H"?(this._oCore.bUseVScroll?'7':'2')+"px":"1px"),"pointerEvents":"none"});if(this.option("bUseFixedScrollbar")){welScrollbar.show();}else{welScrollbar.hide();}
if(sDirection==="H"){welScrollbar.css({height:"5px",left:"2px"});}else{welScrollbar.css({width:"5px",top:"2px"});}
return welScrollbar;},_createScrollbarIndicator:function(sDirection){var welScrollbarIndicator=jindo.$Element("<div>").css({"position":"absolute","zIndex":100,"border":this.option("sScrollbarBorder"),"pointerEvents":"none","left":0,"top":0,"background-color":this.option("sScrollbarColor")});if(this._oCore.isIos){welScrollbarIndicator.css(this._oCore.sCssPrefix+"BorderRadius","12px");}
if(this._oCore.option("bUseTranslate")||this._oCore.option("bUseCss3d")){welScrollbarIndicator.css(this._oCore.sCssPrefix+"TransitionProperty","-webkit-transform").css(this._oCore.sCssPrefix+"Transform","translate"+this._oCore.sTransOpen+"0,0"+this._oCore.sTransEnd);}
if(this._oCore.option("bUseTimingFunction")){welScrollbarIndicator.css(this._oCore.sCssPrefix+"TransitionTimingFunction","cubic-bezier(0.33,0.66,0.66,1)");}
if(sDirection==="H"){welScrollbarIndicator.height(5);}else{welScrollbarIndicator.width(5);}
return welScrollbarIndicator;},_setScrollBarPos:function(sDirection,nPos){if(!(sDirection==="H"?this._oCore.bUseHScroll:this._oCore.bUseVScroll)){return;}
var welIndicator=this._htWElement[sDirection+"scrollbarIndicator"],welScrollbar=this._htWElement[sDirection+"scrollbar"];nPos=this["_nProp"+sDirection+'Scroll']*nPos;if(!this.option("bUseFixedScrollbar")&&!welScrollbar.visible()){welScrollbar.show();}
if(welIndicator){if(this._oCore.option("bUseTranslate")){if(this._oCore.isPositionBug&&this._oCore.bUseHighlight){var nBufferPos=parseInt((sDirection==="H"?welIndicator.css("left"):welIndicator.css("top")),10);nPos-=isNaN(nBufferPos)?0:nBufferPos;}
welIndicator.css(this._oCore.sCssPrefix+"Transform","translate"+this._oCore.sTranOpen+(sDirection==="H"?nPos+"px,0":"0,"+nPos+"px")+this._oCore.sTranEnd);}else{if(sDirection==="H"){welIndicator.css("left",nPos+"px");}else{welIndicator.css("top",nPos+"px");}}}},destroy:function(){this.deactivate();for(var p in this._htWElement){this._htWElement[p]=null;}
this._oCore.destroy();delete this._oCore;this._htWElement=null;}}).extend(jindo.UIComponent);jindo.m.ScrollEnd=jindo.$Class({$init:function(el,htUserOption){this._initVar();this._setWrapperElement(el);this._attachEvent();},_initVar:function(){if(jindo.m.getDeviceInfo().android){if(parseInt(jindo.m.getDeviceInfo().version,10)>=3){this._nType=2;this._nScrollTimer=-1;}else{this._nType=1;}}else{this._nType=0;}
this._isTouched=false;this._isMoved=false;this._nObserver=null;this._nScrollEndTimer=null;this._nPreLeft=null;this._nPreTop=null;},_setWrapperElement:function(el){this._htElement={};this._htElement["body"]=document.body;},_attachEvent:function(){this._htEvent={};this._htEvent["event_scroll"]={ref:jindo.$Fn(this._onScroll,this).attach(window,"scroll"),el:window};if(this._nType==1){this._htEvent["event_touchstart"]={ref:jindo.$Fn(this._onStartForAndroid,this).attach(this._htElement["body"],"touchstart"),el:this._htElement["body"]};this._htEvent["event_touchmove"]={ref:jindo.$Fn(this._onMoveForAndroid,this).attach(this._htElement["body"],"touchmove"),el:this._htElement["body"]};this._htEvent["event_touchend"]={ref:jindo.$Fn(this._onEndForAndroid,this).attach(this._htElement["body"],"touchend"),el:this._htElement["body"]};}},_detachEvent:function(){for(var p in this._htEvent){var ht=this._htEvent[p];ht.ref.detach(ht.el,p.substring(p.lastIndexOf("_")));}},_startObserver:function(){var self=this;this._stopObserver();this._nObserver=setInterval(function(){self._observe();},100);},_observe:function(){if(this._isTouched||(this._nPreTop!==window.pageYOffset||this._nPreLeft!==window.pageXOffset)){this._nPreTop=window.pageYOffset;this._nPreLeft=window.pageXOffset;}else{this._stopObserver();this._fireEventScrollEnd();}},_stopObserver:function(){clearInterval(this._nObserver);this._nObserver=null;},_onScroll:function(we){switch(this._nType){case 0:this._fireEventScrollEnd();break;case 1:this._startObserver();break;case 2:var self=this;clearTimeout(this._nScrollTimer);this._nScrollTimer=setTimeout(function(){self._fireEventScrollEnd();},350);break;}},_onStartForAndroid:function(we){this._isTouched=true;this._isMoved=false;this._nPreTop=null;this._nPreLeft=null;},_onMoveForAndroid:function(we){this._isMoved=true;},_onEndForAndroid:function(we){this._isTouched=false;if(this._isMoved){this._startObserver();}},_fireEventScrollEnd:function(){this.fireEvent("scrollEnd",{nTop:window.pageYOffset,nLeft:window.pageXOffset});},_fireEventScrollEndForAndroid:function(){var self=this;clearTimeout(this._nScrollEndTimer);this._nScrollEndTimer=setTimeout(function(){self._fireEventScrollEnd();},500);},destroy:function(){this._detachEvent();this._nType=-1;this._isTouched=null;this._isMoved=null;this._nObserver=null;this._nPreLeft=null;this._nPreTop=null;}}).extend(jindo.Component);